config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :stories

  devise_for :members ,controllers: { registrations: 'registrations' }
  devise_scope :member do
    get "/members/edit_email" , to: "registrations#edit_email"
  end

  get "timeline" , to: "timeline#index"

  resources :members

  breeze_routes root: true

end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController

  def index
    @weeks = (params[:weeks] || "12").to_i
    @members = Member.visible_scope.
                where("leaving > ? " , Date.today).
                where("arriving < ? " , helpers.start_day + @weeks.weeks).
                order(:arriving).
                page(1).per(50)
  end
end

app/helpers/timeline_helper.rb
module TimelineHelper

  def week_pixels
    70
  end
  def day_pixels
    week_pixels / 7
  end
  def max_days
    @weeks * 7
  end
  def start_day
    Date.today.at_beginning_of_week - 1.week
  end
  # number of days from start of month to start of stay
  def started_days(member)
    return 0 unless member.arriving
    return 0 if member.arriving < start_day
    distance = (member.arriving - start_day).to_i
    distance > max_days ? max_days : distance
  end
  def left_max
    start_day + 3.months
  end

  # amount of days of the stay, maxed at the number fo weeks shown
  def stay_days(member)
    return 0 unless member.leaving
    start = member.arriving
    start = start_day if member.arriving < start_day
    distance = ( member.leaving - start ).to_i
    max = max_days - started_days(member)
    distance > max ? max : distance
  end

  # weekly occupany, hash containing weeks to number of volunteer mapping
  def weekly
    month_start = start_day
    ( 0 ... @weeks ).collect do |week|
      amount = -1
      start_week = month_start + week.weeks
      end_week = start_week + 7.days
      #puts "WEEK #{week}  #{start_week} -- #{end_week}"
      @members.each do |mem|
        #puts "volunteer #{mem.name}"
        next unless mem.arriving
        next unless mem.leaving
        next if mem.leaving <= start_week
        #puts "volunteer #{mem.name} leaving #{mem.leaving}"
        next if mem.arriving >= end_week
        #puts "volunteer #{mem.name} arriving #{mem.arriving}"
        amount += 1
      end
      amount
    end
  end
  def bg_for(week)
    [ "bg-cyan-100",
      "bg-blue-100",
      "bg-violet-100",
      "bg-fuchsia-100",
      "bg-pink-100",
      "bg-rose-100",
      "bg-orange-100",
      "bg-amber-100",
      "bg-yellow-100",
      "bg-lime-100",
      "bg-green-100",
      "bg-teal-100",
    ][week%12]
  end
  def small_date(date)
    date.strftime("%-d.%-m")
  end
end

app/views/timeline/index.haml
.mx-10
  %table.table-fixed.w-full
    %tr
      - ((@weeks - 5)..(@weeks + 5)).each do |week|
        %td.mx-2.mb-2{colspan: 4 , class: week == @weeks ? "bg-orange-100" : "bg-white"}
          =link_to week.to_s , timeline_path( weeks: week)
    %tr
      - (0...@weeks*7).each do |week|
        %td{width: 100.0 / (@weeks * 7)  }
    %tr
      - (0...@weeks).each do |week|
        %td{colspan: 7 , class: bg_for(week + 2)  }
          = small_date(start_day + week.weeks)
    %tr
      - weekly.each_with_index do |amount , week |
        %td{colspan: 7, class: bg_for(week + 2) , style: "width: #{week_pixels}px;"}= amount

    - @members.each_with_index do |member , index|
      %tr{class: bg_for(index)}
        - if( (days = started_days(member)) > 0)
          %td.bg-white{colspan: days }
        - if( (days = stay_days(member)) < 14)
          %td{colspan: days}
            = small_date(member.arriving)
            = link_to member.name , member_url(member)
            = small_date(member.leaving)
        -else
          %td.py-1{colspan: 4,}= small_date(member.arriving)
          %td{colspan: days - 8}= link_to member.name , member_url(member)
          %td{colspan: 4}= small_date(member.leaving)