config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :stories

  devise_for :members ,controllers: { registrations: 'registrations' }
  devise_scope :member do
    get "/members/edit_email" , to: "registrations#edit_email"
  end

  get "timeline" , to: "timeline#index"

  resources :members

  breeze_routes root: true

end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :member

  mount_uploader :picture, PictureUploader

  def self.ransackable_attributes(auth_object = nil)
  ["created_at", "happened", "id", "member_id", "picture", "text", "updated_at"]
  end
  
  validates :text, length: { maximum: 80 }
  validates :happened, presence: true
  validates :picture, presence: true

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]

  def index
    @q = Picture.ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @pictures = @q.result(distinct: true).page( params[:page])
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit
    authorize @picture
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.member = current_member

    if @picture.save
      redirect_to @picture, notice: "Picture was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @picture
    if @picture.update(picture_params)
      redirect_to @picture, notice: "Picture was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @picture
    @picture.destroy
    redirect_to pictures_url, notice: "Picture was successfully destroyed."
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:picture,:picture_cache ,:text,
                            :happened , :member_id)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.haml
%div
  Pictures may have a small text, that will be diplayed on top of the
  picure. The Picture box is landscape with ratio 3/4.
  = simple_form_for @picture do |f|
    = f.error_notification
    .flex.h-16.mt-2
      = image_tag(@picture.picture_url , class: "align-middle mr-2") if @picture.picture?
      .w-full= f.input :picture , as: :file ,
      label: (@picture.picture.blank? ? "Add picture" : "Change picture")
      = f.hidden_field :picture_cache
    = f.input :text , as: :text , input_html: { rows: 2 }
    = f.input :happened , wrapper_class: "flex mt-4 align-center"
    .flex.justify-between.mt-6
      %button.bg-cyan-200.rounded-lg.px-4.py-3.text-md.font-medium.border.border-gray-400
        = f.submit 'Save'
      = link_to member_path(current_member) do
        %button.ml-20.rounded-lg.px-4.py-3.text-md.font-medium.border.border-gray-400
          Back

app/views/pictures/_picture.haml
.group.relative.overflow-hidden
  .flex.justify-between
    .ml-2= link_to picture.member.name , main_app.member_path(picture.member) , class: :underline
    .mr-2
      = distance_of_time_in_words_to_now picture.happened
      ago
  .h-0.overflow-hidden.relative{class: "pt-[75%]"}
    =link_to someones_path( picture ) , {class: :glightbox ,
        "data-glightbox" => "title: #{picture.text}" } do
      = picture_for( picture , "absolute top-0 left-0 w-full h-full inset-0 object-cover hover:scale-105 ease-in duration-500")
  -unless picture.text.blank?
    .absolute.bottom-0.leaving-0.right-0.px-4.pb-1.bg-gray-800.opacity-70.transition-colors.group-hover:bg-black.group-hover:opacity-100
      .text-center.mt-2.text-white= picture.text

app/views/pictures/edit.html.haml
%script{:src => "https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"}
%script{:src => "https://cdn.jsdelivr.net/npm/marked/marked.min.js"}
.flex.justify-center
  .column{class: "w-10/12 md:w-8/12 lg:w-7/12 xl:w-6/12"}
    .text-2xl.font-bold.my-4
      Edit Picture
    = render 'form'

app/views/pictures/index.html.haml
= paginate @pictures

.flex.justify-end.mr-10
  = sort_link(@q, :happened ,class: 'flex flex-nowrap text-md')
  .border-r-4.mx-4
  = sort_link(@q, :created_at , class: 'flex flex-nowrap text-md')

.mx-6.md:mx-12.mx-20.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.2xl:grid-cols-4.gap-8.md:gap-12.lg:gap-16
  - @pictures.each do |picture|
    = render picture , picture: picture

-if current_member
  .flex.ml-20
    = link_to new_picture_path do
      %button.bg-cyan-200.mr-3.inline-block.rounded-lg.px-4.py-3.text-md.font-medium.border.border-gray-400
        New Picture

:javascript
    document.addEventListener("DOMContentLoaded", function(event) {
      const lightbox = GLightbox({  });
    });

app/views/pictures/new.html.haml
%script{:src => "https://cdn.jsdelivr.net/npm/vue@2.7.14/dist/vue.js"}
%script{:src => "https://cdn.jsdelivr.net/npm/marked/marked.min.js"}
.flex.justify-center
  .column{class: "w-10/12 md:w-8/12 lg:w-7/12 xl:w-6/12"}
    .text-2xl.font-bold.my-4
      New Picture
    = render 'form'

app/views/pictures/show.html.haml
.grid.grid-cols-1.md:grid-cols-2.lg:grid-cols-3.gap-8.md:gap-12.lg:gap-16
  %div
  = render @picture , picture: @picture

.mx-6.md:mx-12.mx-20.flex.justify-between
  = link_to edit_picture_path(@picture) do
    %button.mt-6.bg-cyan-200.mr-3.inline-block.rounded-lg.px-4.py-3.text-md.font-medium.border.border-gray-400
      Edit
  = link_to pictures_path do
    %button.mt-6.mr-3.inline-block.rounded-lg.px-4.py-3.text-md.font-medium.border.border-gray-400
      Back